// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    opere,
    serie,
    edizioni,
    copie,
    scansioni,
    analisiOcr,
  ];
  late final Shape0 opere = Shape0(
    source: i0.VersionedTable(
      entityName: 'opere',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 serie = Shape1(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 edizioni = Shape2(
    source: i0.VersionedTable(
      entityName: 'edizioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 copie = Shape3(
    source: i0.VersionedTable(
      entityName: 'copie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scansioni = Shape4(
    source: i0.VersionedTable(
      entityName: 'scansioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_21, _column_22, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 analisiOcr = Shape5(
    source: i0.VersionedTable(
      entityName: 'analisi_ocr',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_24,
        _column_9,
        _column_7,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalIssues =>
      columnsByName['total_issues']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_issues',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get operaId =>
      columnsByName['opera_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serieId =>
      columnsByName['serie_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get issueNumber =>
      columnsByName['issue_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverImage =>
      columnsByName['cover_image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'opera_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES opere(id)',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'serie_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES serie(id)',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'publisher',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'issue_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'issue_number_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_image',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get edizioneId =>
      columnsByName['edizione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get readingStatus =>
      columnsByName['reading_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get condition =>
      columnsByName['condition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get purchasePrice =>
      columnsByName['purchase_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get purchaseDate =>
      columnsByName['purchase_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seller =>
      columnsByName['seller']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'edizione_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES edizioni(id)',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reading_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'condition',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'purchase_price',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'purchase_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'seller',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scansioneId =>
      columnsByName['scansione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seriesName =>
      columnsByName['series_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get isbn =>
      columnsByName['isbn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get price =>
      columnsByName['price']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rawResponse =>
      columnsByName['raw_response']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scansione_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES scansioni(id)',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'series_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'isbn',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'barcode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'price',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'raw_response',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    opere,
    serie,
    edizioni,
    copie,
    scansioni,
    analisiCopertina,
  ];
  late final Shape0 opere = Shape0(
    source: i0.VersionedTable(
      entityName: 'opere',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 serie = Shape1(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 edizioni = Shape2(
    source: i0.VersionedTable(
      entityName: 'edizioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 copie = Shape3(
    source: i0.VersionedTable(
      entityName: 'copie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scansioni = Shape4(
    source: i0.VersionedTable(
      entityName: 'scansioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_21, _column_22, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 analisiCopertina = Shape6(
    source: i0.VersionedTable(
      entityName: 'analisi_copertina',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_24,
        _column_9,
        _column_7,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scansioneId =>
      columnsByName['scansione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seriesName =>
      columnsByName['series_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get isbn =>
      columnsByName['isbn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get price =>
      columnsByName['price']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get characters =>
      columnsByName['characters']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverStyleTags =>
      columnsByName['cover_style_tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get visualElementTags =>
      columnsByName['visual_element_tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recognizedPublisherLogo =>
      columnsByName['recognized_publisher_logo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recognizedSeriesLogo =>
      columnsByName['recognized_series_logo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rawResponse =>
      columnsByName['raw_response']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'characters',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_style_tags',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'visual_element_tags',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recognized_publisher_logo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recognized_series_logo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    opere,
    serie,
    edizioni,
    scansioni,
    copie,
    analisiCopertina,
    identificazione,
    candidati,
  ];
  late final Shape0 opere = Shape0(
    source: i0.VersionedTable(
      entityName: 'opere',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 serie = Shape1(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 edizioni = Shape2(
    source: i0.VersionedTable(
      entityName: 'edizioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scansioni = Shape4(
    source: i0.VersionedTable(
      entityName: 'scansioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_21, _column_22, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 copie = Shape7(
    source: i0.VersionedTable(
      entityName: 'copie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_20,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 analisiCopertina = Shape6(
    source: i0.VersionedTable(
      entityName: 'analisi_copertina',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_24,
        _column_9,
        _column_7,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 identificazione = Shape8(
    source: i0.VersionedTable(
      entityName: 'identificazione',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_30,
        _column_31,
        _column_2,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 candidati = Shape9(
    source: i0.VersionedTable(
      entityName: 'candidati',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_40,
        _column_41,
        _column_24,
        _column_25,
        _column_9,
        _column_7,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get edizioneId =>
      columnsByName['edizione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get readingStatus =>
      columnsByName['reading_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get condition =>
      columnsByName['condition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get purchasePrice =>
      columnsByName['purchase_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get purchaseDate =>
      columnsByName['purchase_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seller =>
      columnsByName['seller']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scansioneId =>
      columnsByName['scansione_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scansione_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES scansioni(id)',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scansioneId =>
      columnsByName['scansione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get identificazioneId =>
      columnsByName['identificazione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get edizioneId =>
      columnsByName['edizione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seriesName =>
      columnsByName['series_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get coverImageUrl =>
      columnsByName['cover_image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get punteggio =>
      columnsByName['punteggio']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get scelto =>
      columnsByName['scelto']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'identificazione_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES identificazione(id)',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'edizione_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES edizioni(id)',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_image_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'punteggio',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scelto',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (scelto IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    opere,
    serie,
    edizioni,
    scansioni,
    copie,
    analisiCopertina,
    identificazione,
    candidati,
  ];
  late final Shape0 opere = Shape0(
    source: i0.VersionedTable(
      entityName: 'opere',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 serie = Shape10(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4, _column_46],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 edizioni = Shape11(
    source: i0.VersionedTable(
      entityName: 'edizioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scansioni = Shape4(
    source: i0.VersionedTable(
      entityName: 'scansioni',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_21, _column_22, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 copie = Shape7(
    source: i0.VersionedTable(
      entityName: 'copie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_20,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 analisiCopertina = Shape12(
    source: i0.VersionedTable(
      entityName: 'analisi_copertina',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_24,
        _column_9,
        _column_7,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_47,
        _column_49,
        _column_50,
        _column_51,
        _column_46,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 identificazione = Shape8(
    source: i0.VersionedTable(
      entityName: 'identificazione',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_30,
        _column_31,
        _column_2,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 candidati = Shape9(
    source: i0.VersionedTable(
      entityName: 'candidati',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_39,
        _column_40,
        _column_41,
        _column_24,
        _column_25,
        _column_9,
        _column_7,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalIssues =>
      columnsByName['total_issues']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get issn =>
      columnsByName['issn']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'issn',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get operaId =>
      columnsByName['opera_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serieId =>
      columnsByName['serie_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get issueNumber =>
      columnsByName['issue_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverImage =>
      columnsByName['cover_image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get releaseDate =>
      columnsByName['release_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverPrice =>
      columnsByName['cover_price']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pageCount =>
      columnsByName['page_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ean =>
      columnsByName['ean']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'release_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_price',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'page_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ean',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scansioneId =>
      columnsByName['scansione_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get issueNumberLabel =>
      columnsByName['issue_number_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publisher =>
      columnsByName['publisher']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seriesName =>
      columnsByName['series_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get isbn =>
      columnsByName['isbn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get price =>
      columnsByName['price']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get releaseDate =>
      columnsByName['release_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pageCount =>
      columnsByName['page_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get issn =>
      columnsByName['issn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get characters =>
      columnsByName['characters']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverStyleTags =>
      columnsByName['cover_style_tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get visualElementTags =>
      columnsByName['visual_element_tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recognizedPublisherLogo =>
      columnsByName['recognized_publisher_logo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recognizedSeriesLogo =>
      columnsByName['recognized_series_logo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rawResponse =>
      columnsByName['raw_response']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
