#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# GitHub issue #169 ("Task — configurare Google Sign-In (Google Cloud +
# Supabase Auth)", child della mappa wayfinder #165). Come per Apple
# (scripts/setup-apple-signin.sh) i valori stanno fuori dal repo, in un env
# file dedicato in home. Assegnazione diretta: la libreria sopra ha già
# valorizzato ENV_FILE a ".env".
ENV_FILE="$HOME/.mycomicbrain-google-signin.env"
BUNDLE_ID="com.saviogiordano.mycomicbrain.mycomicbrain"
ANDROID_PACKAGE="com.saviogiordano.mycomicbrain.mycomicbrain"
SUPABASE_PROJECT_REF="ojfwicezfctlwpouudsa"
SUPABASE_CALLBACK_URL="https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"
DEBUG_KEYSTORE="$HOME/.android/debug.keystore"

touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

banner "Google Sign-In — Google Cloud + Supabase Auth"

# ── Stage 1: progetto Google Cloud ──────────────────────────────────────────
stage "Progetto Google Cloud"
open_url "https://console.cloud.google.com/projectcreate"
step "Crea un progetto (es. \"MyComicBrain\"), oppure selezionane uno esistente dal selettore in alto."
step "Copia il Project ID (non il nome): è mostrato sotto il nome durante la creazione e nella dashboard."
ask GOOGLE_CLOUD_PROJECT_ID "Project ID Google Cloud:"
write_env GOOGLE_CLOUD_PROJECT_ID "$GOOGLE_CLOUD_PROJECT_ID"

# ── Stage 2: schermata di consenso OAuth ───────────────────────────────────
stage "Schermata di consenso OAuth (Google Auth Platform)"
open_url "https://console.cloud.google.com/auth/overview?project=${GOOGLE_CLOUD_PROJECT_ID}"
step "Se richiesto, premi \"Get started\": nome app \"MyComicBrain\", email di supporto, Audience \"External\", email di contatto."
step "Data Access → Add or remove scopes: seleziona openid, .../auth/userinfo.email, .../auth/userinfo.profile → Save."
step "Audience: finché l'app è in \"Testing\" possono accedere solo i Test users — aggiungi il tuo account Google."
note "Con soli scope openid/email/profile la pubblicazione (\"Publish app\") non richiede verifica Google:"
note "si potrà fare quando il login esce dal flag di sviluppo."
pause "Premi Invio quando la schermata di consenso è salvata."

# ── Stage 3: client Web (usato da Supabase) ────────────────────────────────
stage "Client OAuth — Web application (per Supabase)"
open_url "https://console.cloud.google.com/auth/clients/create?project=${GOOGLE_CLOUD_PROJECT_ID}"
step "Application type: Web application · Name: \"MyComicBrain — Supabase\"."
step "Authorized redirect URIs → Add URI: $SUPABASE_CALLBACK_URL"
step "Create, poi copia Client ID e Client secret dalla finestra di conferma."
ask GOOGLE_WEB_CLIENT_ID "Client ID Web (…apps.googleusercontent.com):"
write_env GOOGLE_WEB_CLIENT_ID "$GOOGLE_WEB_CLIENT_ID"
ask_secret GOOGLE_WEB_CLIENT_SECRET "Client secret Web (input nascosto):"
write_env GOOGLE_WEB_CLIENT_SECRET "$GOOGLE_WEB_CLIENT_SECRET"

# ── Stage 4: client iOS ──────────────────────────────────────────────────────
stage "Client OAuth — iOS"
open_url "https://console.cloud.google.com/auth/clients/create?project=${GOOGLE_CLOUD_PROJECT_ID}"
step "Application type: iOS · Name: \"MyComicBrain — iOS\"."
step "Bundle ID: $BUNDLE_ID (App Store ID e Team ID sono facoltativi)."
step "Create, poi copia il Client ID."
ask GOOGLE_IOS_CLIENT_ID "Client ID iOS:"
write_env GOOGLE_IOS_CLIENT_ID "$GOOGLE_IOS_CLIENT_ID"
# Schema URL per CFBundleURLTypes: il client ID con i segmenti invertiti.
GOOGLE_IOS_REVERSED_CLIENT_ID="com.googleusercontent.apps.${GOOGLE_IOS_CLIENT_ID%.apps.googleusercontent.com}"
write_env GOOGLE_IOS_REVERSED_CLIENT_ID "$GOOGLE_IOS_REVERSED_CLIENT_ID"

# ── Stage 5: client Android (chiave di debug) ─────────────────────────────
stage "Client OAuth — Android (chiave di debug)"
GOOGLE_ANDROID_DEBUG_SHA1=""
if [[ -f "$DEBUG_KEYSTORE" ]] && command -v keytool >/dev/null 2>&1; then
  GOOGLE_ANDROID_DEBUG_SHA1=$(keytool -list -v -keystore "$DEBUG_KEYSTORE" \
    -alias androiddebugkey -storepass android -keypass android 2>/dev/null \
    | awk '/SHA1:/ {print $2; exit}') || true
fi
if [[ -n "$GOOGLE_ANDROID_DEBUG_SHA1" ]]; then
  printf '  %s✓ SHA-1 di debug%s %s\n' "$GREEN" "$RESET" "$GOOGLE_ANDROID_DEBUG_SHA1"
else
  warn "SHA-1 non calcolato ($DEBUG_KEYSTORE o keytool mancanti): lancia una build Android una volta e rilancia"
  ask GOOGLE_ANDROID_DEBUG_SHA1 "SHA-1 di debug (se lo conosci già):"
fi
write_env GOOGLE_ANDROID_DEBUG_SHA1 "$GOOGLE_ANDROID_DEBUG_SHA1"
open_url "https://console.cloud.google.com/auth/clients/create?project=${GOOGLE_CLOUD_PROJECT_ID}"
step "Application type: Android · Name: \"MyComicBrain — Android debug\"."
step "Package name: $ANDROID_PACKAGE"
step "SHA-1 certificate fingerprint: $GOOGLE_ANDROID_DEBUG_SHA1"
step "Create, poi copia il Client ID (non va nel codice: serve solo a Supabase)."
ask GOOGLE_ANDROID_DEBUG_CLIENT_ID "Client ID Android debug:"
write_env GOOGLE_ANDROID_DEBUG_CLIENT_ID "$GOOGLE_ANDROID_DEBUG_CLIENT_ID"
note "Client di release rimandato: oggi le build release sono firmate con la chiave di debug."
SKIPPED+=("client Android di release: quando esisterà la chiave di upload (e lo SHA-1 di Play App Signing), crea un client Android per ciascuno e aggiungili ai Client IDs su Supabase")

# ── Stage 6: provider Google in Supabase Auth ─────────────────────────────
stage "Supabase Auth — provider Google"
SUPABASE_GOOGLE_CLIENT_IDS="${GOOGLE_WEB_CLIENT_ID},${GOOGLE_IOS_CLIENT_ID},${GOOGLE_ANDROID_DEBUG_CLIENT_ID}"
write_env SUPABASE_GOOGLE_CLIENT_IDS "$SUPABASE_GOOGLE_CLIENT_IDS"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "Apri \"Google\" e abilita \"Enable Sign in with Google\"."
step "Client IDs (il client Web deve essere il PRIMO):"
say "    $SUPABASE_GOOGLE_CLIENT_IDS"
step "Client Secret (for OAuth): il secret del client Web (stage 3), lo trovi in $ENV_FILE"
step "Attiva \"Skip nonce checks\" (richiesto da iOS, vale per tutto il provider)."
step "Verifica che la Callback URL mostrata sia $SUPABASE_CALLBACK_URL, poi Save."
pause "Premi Invio quando il provider Google risulta salvato su Supabase."

finish

# ── Riepilogo per il commento di chiusura su GitHub (#169) ────────────────
printf '%s%s  Riepilogo per il ticket GitHub #169%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "Solo identificatori, nessun segreto: incollalo in chat o come commento su #169."
printf '\n---\n'
printf 'Project ID Google Cloud: %s\n' "$(_existing GOOGLE_CLOUD_PROJECT_ID || echo '(mancante)')"
printf 'Client ID Web: %s\n' "$(_existing GOOGLE_WEB_CLIENT_ID || echo '(mancante)')"
printf 'Client ID iOS: %s\n' "$(_existing GOOGLE_IOS_CLIENT_ID || echo '(mancante)')"
printf 'Reversed client ID iOS: %s\n' "$(_existing GOOGLE_IOS_REVERSED_CLIENT_ID || echo '(mancante)')"
printf 'Client ID Android debug: %s\n' "$(_existing GOOGLE_ANDROID_DEBUG_CLIENT_ID || echo '(mancante)')"
printf 'SHA-1 debug: %s\n' "$(_existing GOOGLE_ANDROID_DEBUG_SHA1 || echo '(mancante)')"
printf 'Client secret Web: in %s (GOOGLE_WEB_CLIENT_SECRET)\n' "$ENV_FILE"
printf -- '---\n\n'
