#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# GitHub issue #156 ("Task — attivare Apple Developer Program e configurare
# Sign in with Apple", child del wayfinder map #149) chiede questi valori
# fuori dal repo: usiamo un env file dedicato in home, non l'.env di progetto.
# Assegnazione diretta (non ${ENV_FILE:-...}): la libreria sopra ha già
# valorizzato ENV_FILE a ".env", quindi un fallback qui non scatterebbe mai.
ENV_FILE="$HOME/.mycomicbrain-apple-signin.env"
KEY_DIR="${KEY_DIR:-$HOME/.mycomicbrain-secrets/apple-signin}"
DEFAULT_BUNDLE_ID="com.saviogiordano.mycomicbrain.mycomicbrain"

banner "Sign in with Apple — Apple Developer Program + Supabase Auth"

# ── Stage 1: iscrizione al programma ───────────────────────────────────────
stage "Apple Developer Program — iscrizione"
say "Offrire login social di terze parti (Google/Facebook) su iOS obbliga, per"
say "la App Store Review Guideline 4.8, a offrire anche \"Sign in with Apple\"."
say "Serve un account Apple Developer Program attivo: \$99/anno, richiede un"
say "Apple ID con 2FA attiva e un metodo di pagamento."
if confirm "Sei già iscritto al programma (account attivo)?"; then
  note "ok, salto l'iscrizione"
else
  open_url "https://developer.apple.com/programs/enroll/"
  step "Accedi con il tuo Apple ID (attiva la 2FA se non l'hai già fatta)."
  step "Scegli iscrizione individuale o come organizzazione, completa dati e pagamento."
  note "L'attivazione può richiedere da pochi minuti fino a 48 ore (verifica Apple)."
  pause "Premi Invio quando l'iscrizione risulta attiva (o interrompi con Ctrl-C e rilancia più tardi)."
fi

# ── Stage 2: Team ID ────────────────────────────────────────────────────────
stage "Team ID"
open_url "https://developer.apple.com/account/#/membership"
step "Nella pagina Membership, copia il Team ID (10 caratteri, sotto \"Membership Details\")."
ask APPLE_TEAM_ID "Team ID:"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── Stage 3: App ID con capability Sign In with Apple ──────────────────────
stage "App ID — capability \"Sign In with Apple\""
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Crea (o apri se esiste già) l'App ID per il Bundle ID dell'app: $DEFAULT_BUNDLE_ID"
step "Nella sezione Capabilities, abilita \"Sign In with Apple\" e salva."
ask APPLE_BUNDLE_ID "Bundle ID [Invio = $DEFAULT_BUNDLE_ID]:"
APPLE_BUNDLE_ID="${APPLE_BUNDLE_ID:-$DEFAULT_BUNDLE_ID}"
write_env APPLE_BUNDLE_ID "$APPLE_BUNDLE_ID"

# ── Stage 4: Services ID (client_id per Supabase) ──────────────────────────
stage "Services ID — client_id per Supabase"
open_url "https://developer.apple.com/account/resources/identifiers/list/serviceId"
step "Crea un nuovo Services ID, es. ${APPLE_BUNDLE_ID}.signin — sarà il client_id in Supabase."
step "Abilita \"Sign In with Apple\" e associalo all'App ID dello Stage 3."
ask APPLE_SERVICES_ID "Services ID (client_id):"
write_env APPLE_SERVICES_ID "$APPLE_SERVICES_ID"
say "Se conosci già il project ref Supabase, configuriamo dominio e Return URL ora."
say "Altrimenti lascia vuoto: si potrà completare più avanti (Stage 6)."
ask SUPABASE_PROJECT_REF "Project ref Supabase [Invio se non esiste ancora]:"
if [[ -n "$SUPABASE_PROJECT_REF" ]]; then
  write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
  SUPABASE_DOMAIN="${SUPABASE_PROJECT_REF}.supabase.co"
  SUPABASE_RETURN_URL="https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"
  say "Torna sul Services ID appena creato, sezione \"Sign In with Apple\" → Configure, e imposta:"
  step "Domains and Subdomains: $SUPABASE_DOMAIN"
  step "Return URLs: $SUPABASE_RETURN_URL"
  pause "Premi Invio quando hai salvato dominio e Return URL."
else
  SKIPPED+=("Services ID: configurare dominio/Return URL quando il progetto Supabase esisterà")
  warn "dominio e Return URL rimandati — il progetto Supabase non esiste ancora"
fi

# ── Stage 5: chiave privata .p8 ─────────────────────────────────────────────
stage "Chiave privata (.p8)"
open_url "https://developer.apple.com/account/resources/authkeys/list"
step "Crea una nuova Key, abilita \"Sign In with Apple\" e associala all'App ID dello Stage 3."
step "Scarica il file .p8 — è scaricabile una sola volta, Apple non lo ridistribuisce."
ask APPLE_KEY_ID "Key ID:"
write_env APPLE_KEY_ID "$APPLE_KEY_ID"
ask APPLE_P8_SRC_PATH "Percorso del file .p8 appena scaricato (es. ~/Downloads/AuthKey_XXXX.p8):"
APPLE_P8_SRC_PATH="${APPLE_P8_SRC_PATH/#\~/$HOME}"
if [[ -f "$APPLE_P8_SRC_PATH" ]]; then
  mkdir -p "$KEY_DIR"
  chmod 700 "$KEY_DIR"
  APPLE_P8_PATH="$KEY_DIR/AuthKey_${APPLE_KEY_ID}.p8"
  cp "$APPLE_P8_SRC_PATH" "$APPLE_P8_PATH"
  chmod 600 "$APPLE_P8_PATH"
  # Solo il percorso finisce nell'env file: mai il contenuto della chiave.
  write_env APPLE_P8_PATH "$APPLE_P8_PATH"
  printf '  %s✓ copiata%s la chiave in %s (permessi 600)\n' "$GREEN" "$RESET" "$APPLE_P8_PATH"
else
  SKIPPED+=("chiave .p8 non trovata in $APPLE_P8_SRC_PATH — copiala manualmente e rilancia lo script")
  warn "file non trovato: $APPLE_P8_SRC_PATH — potrai rilanciare lo script più tardi"
fi

# ── Stage 6: provider Apple in Supabase Auth (skippabile) ─────────────────
stage "Supabase Auth — provider Apple"
if confirm "Il progetto Supabase esiste già ed è pronto per la configurazione?"; then
  ask SUPABASE_PROJECT_REF "Project ref Supabase:"
  write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
  step "Abilita il provider \"Apple\"."
  step "Client ID: $APPLE_SERVICES_ID"
  step "Team ID: $APPLE_TEAM_ID"
  step "Key ID: $APPLE_KEY_ID"
  if [[ -n "${APPLE_P8_PATH:-}" ]]; then
    step "Private key: apri $APPLE_P8_PATH e incolla il contenuto nel campo dedicato."
  else
    step "Private key: incolla il contenuto del file .p8 dello Stage 5 (non ancora salvato — completalo prima)."
  fi
  pause "Premi Invio quando il provider Apple risulta salvato su Supabase."
else
  SKIPPED+=("provider Apple su Supabase Auth — progetto Supabase non ancora pronto, rilancia lo script più tardi")
  note "salto: rilancia questo script quando il progetto Supabase sarà pronto"
fi

finish

# ── Riepilogo per il commento di chiusura su GitHub (#156) ────────────────
_clear
printf '\n%s%s  Riepilogo per il ticket GitHub #156%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "Incolla questo blocco come commento su #156 (nessun segreto, solo identificatori):"
printf '\n---\n'
printf 'Team ID: %s\n' "$(_existing APPLE_TEAM_ID || echo '(non ancora raccolto)')"
printf 'Bundle ID: %s\n' "$(_existing APPLE_BUNDLE_ID || echo '(non ancora raccolto)')"
printf 'Services ID (client_id): %s\n' "$(_existing APPLE_SERVICES_ID || echo '(non ancora raccolto)')"
printf 'Key ID: %s\n' "$(_existing APPLE_KEY_ID || echo '(non ancora raccolto)')"
printf 'Project ref Supabase: %s\n' "$(_existing SUPABASE_PROJECT_REF || echo '(non ancora esistente)')"
printf 'Percorso chiave .p8: %s\n' "$(_existing APPLE_P8_PATH || echo '(non ancora salvata)')"
printf -- '---\n\n'
note "comando pronto: gh issue comment 156 --body \"...\" (poi gh issue close 156)"
