-- Scansioni e Conversazione: sempre private all'account che le ha create,
-- anche dentro una Collezione condivisa (ADR-0004). Ogni tabella ha una
-- colonna `user_id` diretta (niente join nelle policy); le FK fra tabelle
-- private sono composite su (user_id, <fk>), così una riga non può puntare
-- al lavoro di un altro utente. Stesse convenzioni di mapping di
-- 20260925090100_catalogo.sql.

create table public.scansioni (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- Informativo (la Collezione che riceverà la Copia): non entra nelle policy.
  collection_id uuid references public.collections (id) on delete set null,
  -- Chiave Storage nel bucket `scansioni` (<user_id>/<uuid>.jpg), non un URL.
  image text not null,
  created_at timestamptz not null default now(),
  unique (user_id, id)
);

create table public.analisi_copertina (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  scansione_id bigint not null,
  title text,
  issue_number_label text,
  publisher text,
  series_name text,
  isbn text,
  barcode text,
  price text,
  release_date text,
  year integer,
  page_count integer,
  language text,
  color text,
  issn text,
  characters text[] not null default '{}',
  cover_style_tags text[] not null default '{}',
  visual_element_tags text[] not null default '{}',
  recognized_publisher_logo text,
  recognized_series_logo text,
  printing_type text,
  classificazione text,
  description text,
  raw_response text,
  status text not null default 'pending'
    check (status in ('pending', 'inCorso', 'completata', 'fallita')),
  error_message text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, id),
  foreign key (user_id, scansione_id) references public.scansioni (user_id, id) on delete cascade
);

create table public.identificazione (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  scansione_id bigint not null,
  status text not null default 'pending'
    check (status in ('pending', 'inCorso', 'completata', 'fallita')),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (user_id, id),
  foreign key (user_id, scansione_id) references public.scansioni (user_id, id) on delete cascade
);

create table public.candidati (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  identificazione_id bigint not null,
  source text not null check (source in ('interno', 'esterno')),
  -- Edizione di una Collezione: set null se l'Edizione (o la Collezione)
  -- sparisce, il Candidato resta come traccia dell'Identificazione.
  edizione_id bigint references public.edizioni (id) on delete set null,
  title text,
  series_name text,
  issue_number_label text,
  publisher text,
  year integer,
  cover_image_url text,
  punteggio double precision not null,
  scelto boolean not null default false,
  -- Colonna morta in drift (#73): non portata.
  unique (user_id, id),
  foreign key (user_id, identificazione_id)
    references public.identificazione (user_id, id) on delete cascade
);

create table public.conversazione (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, id)
);

create table public.messaggio (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  conversazione_id bigint not null,
  ruolo text not null check (ruolo in ('utente', 'assistente', 'sistema')),
  sottotipo_sistema text
    check (sottotipo_sistema in ('erroreRete', 'erroreProvider', 'infoSttFallback')),
  testo text not null,
  -- Riferimento vivo a Edizioni, risolto a runtime (nessuna FK, come in drift).
  edizione_ids bigint[],
  created_at timestamptz not null default now(),
  unique (user_id, id),
  foreign key (user_id, conversazione_id)
    references public.conversazione (user_id, id) on delete cascade
);

-- Copia nata da una Scansione: la Copia (dato della Collezione) sopravvive
-- alla Scansione (privata, cancellata con l'account di chi l'ha fatta).
alter table public.copie
  add constraint copie_scansione_id_fkey
  foreign key (scansione_id) references public.scansioni (id) on delete set null;

create index scansioni_collection_id_idx on public.scansioni (collection_id);
create index analisi_copertina_scansione_id_idx on public.analisi_copertina (user_id, scansione_id);
create index identificazione_scansione_id_idx on public.identificazione (user_id, scansione_id);
create index candidati_identificazione_id_idx on public.candidati (user_id, identificazione_id);
create index candidati_edizione_id_idx on public.candidati (edizione_id);
create index messaggio_conversazione_id_idx on public.messaggio (user_id, conversazione_id);

-- RLS: solo chi le ha create ------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array[
    'scansioni', 'analisi_copertina', 'identificazione', 'candidati',
    'conversazione', 'messaggio'
  ] loop
    execute format('alter table public.%I enable row level security', t);

    execute format($p$
      create policy "creator reads own rows" on public.%I
      for select to authenticated
      using ( user_id = (select auth.uid()) )
    $p$, t);

    execute format($p$
      create policy "creator writes own rows" on public.%I
      for all to authenticated
      using ( user_id = (select auth.uid()) )
      with check ( user_id = (select auth.uid()) )
    $p$, t);
  end loop;
end;
$$;
