-- Tabelle di dominio della Collezione (ADR-0004), mappate dalle tabelle drift
-- di app/lib/core/data/database.dart (schemaVersion 15).
--
-- Convenzioni di mapping:
-- - nomi di tabella e colonna identici a quelli SQL generati da drift
--   (snake_case), così adapter e importazione mappano 1:1;
-- - `id` bigint identity; gli id drift non vengono conservati, l'importazione
--   li rimappa (ADR-0007);
-- - DateTimeColumn -> timestamptz; RealColumn -> double precision;
-- - textEnum -> text con vincolo check sui valori `.name` dell'enum Dart
--   (aggiungere un valore = una migrazione che sostituisce il check);
-- - ogni tabella ha `collection_id` + `created_by` e un vincolo
--   unique (collection_id, id): le FK fra tabelle di dominio sono composite
--   su (collection_id, <fk>), così una riga non può mai puntare a una riga
--   di un'altra Collezione.

create table public.opere (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  title text not null,
  created_at timestamptz not null default now(),
  unique (collection_id, id)
);

create table public.serie (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  name text not null,
  total_issues integer,
  issn text,
  cover_image text,
  unique (collection_id, id)
);

create table public.edizioni (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  opera_id bigint not null,
  serie_id bigint,
  publisher text,
  issue_number integer,
  issue_number_label text,
  cover_image text,
  release_date text,
  cover_price text,
  page_count integer,
  language text,
  color text,
  ean text,
  created_at timestamptz not null default now(),
  volume text,
  description text,
  printing_type text,
  classificazione text,
  year integer,
  format text check (format in (
    'spillato', 'bonellide', 'brossurato', 'cartonato', 'tankobon', 'omnibus'
  )),
  unique (collection_id, id),
  foreign key (collection_id, opera_id) references public.opere (collection_id, id),
  foreign key (collection_id, serie_id) references public.serie (collection_id, id)
);

create table public.copie (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  edizione_id bigint not null,
  status text not null check (status in ('posseduta', 'prestata', 'venduta', 'persa')),
  reading_status text check (reading_status in ('daLeggere', 'inLettura', 'letto', 'daRileggere')),
  condition text check (condition in (
    'mint', 'nearMint', 'veryFine', 'fine', 'veryGood', 'good', 'fair', 'poor'
  )),
  purchase_price double precision,
  purchase_price_currency text check (purchase_price_currency in ('eur', 'usd')),
  purchase_date timestamptz,
  seller text,
  valutazione double precision,
  location text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- FK verso scansioni aggiunta nella migrazione delle tabelle private.
  scansione_id bigint,
  for_sale boolean not null default false,
  unique (collection_id, id),
  foreign key (collection_id, edizione_id) references public.edizioni (collection_id, id)
);

create table public.creator (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  name text not null,
  unique (collection_id, id)
);

create table public.comic_creator (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  edizione_id bigint not null,
  creator_id bigint not null,
  ruolo text not null check (ruolo in (
    'sceneggiatore', 'disegnatore', 'inchiostratore', 'colorista',
    'letterista', 'copertinista', 'altro'
  )),
  unique (collection_id, id),
  unique (edizione_id, creator_id, ruolo),
  foreign key (collection_id, edizione_id) references public.edizioni (collection_id, id),
  foreign key (collection_id, creator_id) references public.creator (collection_id, id)
);

create table public.tag (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  name text not null,
  unique (collection_id, id)
);

create table public.edizione_tag (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  edizione_id bigint not null,
  tag_id bigint not null,
  unique (collection_id, id),
  unique (edizione_id, tag_id),
  foreign key (collection_id, edizione_id) references public.edizioni (collection_id, id),
  foreign key (collection_id, tag_id) references public.tag (collection_id, id)
);

create table public.character (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  name text not null,
  unique (collection_id, id)
);

create table public.comic_character (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  edizione_id bigint not null,
  character_id bigint not null,
  unique (collection_id, id),
  unique (edizione_id, character_id),
  foreign key (collection_id, edizione_id) references public.edizioni (collection_id, id),
  foreign key (collection_id, character_id) references public.character (collection_id, id)
);

create table public.edizione_genere (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  edizione_id bigint not null,
  genere text not null check (genere in (
    'supereroi', 'azioneAvventura', 'fantascienza', 'fantasy', 'horror',
    'gialloNoir', 'commedia', 'drammatico', 'romantico', 'storico',
    'sliceOfLife', 'eroticoAdulti'
  )),
  unique (collection_id, id),
  unique (edizione_id, genere),
  foreign key (collection_id, edizione_id) references public.edizioni (collection_id, id)
);

create table public.valore_stimato (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  created_by uuid default auth.uid() references public.profiles (id),
  copia_id bigint not null,
  status text not null check (status in ('inCorso', 'completata', 'nonDisponibile', 'fallita')),
  value double precision,
  error_message text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (collection_id, id),
  unique (copia_id),
  foreign key (collection_id, copia_id) references public.copie (collection_id, id)
);

-- Indici sulle FK (Postgres non li crea da solo) ------------------------------

create index edizioni_opera_id_idx on public.edizioni (collection_id, opera_id);
create index edizioni_serie_id_idx on public.edizioni (collection_id, serie_id);
create index copie_edizione_id_idx on public.copie (collection_id, edizione_id);
create index copie_scansione_id_idx on public.copie (scansione_id);
create index comic_creator_creator_id_idx on public.comic_creator (collection_id, creator_id);
create index comic_creator_edizione_id_idx on public.comic_creator (collection_id, edizione_id);
create index edizione_tag_tag_id_idx on public.edizione_tag (collection_id, tag_id);
create index edizione_tag_edizione_id_idx on public.edizione_tag (collection_id, edizione_id);
create index comic_character_character_id_idx on public.comic_character (collection_id, character_id);
create index comic_character_edizione_id_idx on public.comic_character (collection_id, edizione_id);
create index edizione_genere_edizione_id_idx on public.edizione_genere (collection_id, edizione_id);
create index valore_stimato_copia_id_idx on public.valore_stimato (collection_id, copia_id);

-- RLS: le stesse quattro policy su ogni tabella di dominio ----------------------
-- (l'indice unique (collection_id, id) copre anche i filtri su collection_id).

do $$
declare
  t text;
begin
  foreach t in array array[
    'opere', 'serie', 'edizioni', 'copie', 'creator', 'comic_creator', 'tag',
    'edizione_tag', 'character', 'comic_character', 'edizione_genere',
    'valore_stimato'
  ] loop
    execute format('create index %I on public.%I (created_by)', t || '_created_by_idx', t);
    execute format('alter table public.%I enable row level security', t);

    execute format($p$
      create policy "collection members read" on public.%I
      for select to authenticated
      using ( collection_id in (select private.visible_collection_ids()) )
    $p$, t);

    execute format($p$
      create policy "owner and editor insert" on public.%I
      for insert to authenticated
      with check ( collection_id in (select private.editable_collection_ids()) )
    $p$, t);

    execute format($p$
      create policy "owner and editor update" on public.%I
      for update to authenticated
      using ( collection_id in (select private.editable_collection_ids()) )
      with check ( collection_id in (select private.editable_collection_ids()) )
    $p$, t);

    execute format($p$
      create policy "owner and editor delete" on public.%I
      for delete to authenticated
      using ( collection_id in (select private.editable_collection_ids()) )
    $p$, t);
  end loop;
end;
$$;
